# Автор плагина: https://t.me/tik_boost
# Переводы плагина: https://github.com/katze225/PowerAntiRelog/tree/main/translations

settings:
  # Длительность режима PvP
  time: 25

  bossbar:
    bar: "&fРежим §x§E§3§2§6§3§6PvP &f- §x§E§3§2§6§3§6{time} сек"
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
    color: RED
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
    style: SOLID

  leave:
    kill: true
    # null или [] чтобы отключить
    message:
      - "&r"
      - "§x§E§3§2§6§3§6&l| &fИгрок §x§E§3§2§6§3§6{player}, &fпокинул сервер во время PvP!"
      - "&r"

  # Что будет отключено в начале боя
  disable:
    fly: true
    speed: false
    gamemode: false
    godmode: false
    elytra: false
    invisibility: false

  # Какие действия нужно отменять во время боя
  cancel:
    interact: true
    command: true
    teleport: true
    ender-chest: true

  # Установите 0, чтобы отключить задержки
  cooldown:
    golden-apple: 0
    enchanted-golden-apple: 0
    ender-pearl: 0
    chorus: 0
    firework: 0
    totem: 0
    trident: 0
    crossbow: 0

  # Работает только если cancel.command ровно true
  command-whitelist:
    - "msg"
    - "m"
    - "tell"
    - "pm"

  # Команды в начале или конце боя. Заполнители: {player}, [console], [player]. Выполняется для каждого игрока отдельно!
  # Пример: "[console] msg {player} Удачи в бою!"
  command-start: []
  command-end: []

  # Миры в которых плагин не будет работать
  disabled-worlds:
    - "duels"
    - "duel"
    - "exampleWorld"

messages:
  start: "§x§E§3§2§6§3§6&l| &fВы начали PvP!"
  end: "§x§E§3§2§6§3§6&l| &aВы больше не находитесь в бою."
  block: "§x§E§3§2§6§3§6&l| &cВы не можете делать это в режиме PvP!"
  cooldown: "§x§E§3§2§6§3§6&l| &fПодождите §x§E§3§2§6§3§6{time}, &fчтобы использовать этот предмет!"

  # Установите "", чтобы отключить
  cooldown-subtitle: "&fПодождите §x§E§3§2§6§3§6{time}, &fчтобы использовать этот предмет!"

  help:
    - "&r"
    - "§x§E§3§2§6§3§6PowerAntiRelog:"
    - "&7- §x§E§3§2§6§3§6/powerantirelog help &7- &fСписок команд"
    - "&7- §x§E§3§2§6§3§6/powerantirelog reload &7- &fПерезагружает конфигурацию"
    - "&7- §x§E§3§2§6§3§6/powerantirelog test {игрок} &7- &fВыдаёт игроку режим боя"
    - "&r"
  reload: "§x§E§3§2§6§3§6&l| &aКонфигурация плагина была успешно перезагружена!"
  test: "§x§E§3§2§6§3§6&l| &fВы выдали игроку §x§E§3§2§6§3§6{player} &fрежим PvP."
  not-found: "§x§E§3§2§6§3§6&l| &cИгрок {player} не найден."
