# https://discord.gg/6wGy3sYxzw

settings:
  time: 25

  bossbar:
    bar: "&fРежим §x§E§3§2§6§3§6PvP &f- §x§E§3§2§6§3§6{time} сек"
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
    color: RED
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
    style: SOLID

  leave:
    kill: true
    # null или [] чтобы отключить
    message:
      - "&r"
      - "&fИгрок §x§0§0§A§4§F§B{player}, &fпокинул сервер во время PvP!"
      - "&r"
    # Игрока будет убивать за выход с сервера, если leave.kill включен.
    # Но если игрока кикнет его убьет только в случае данных причин.
    # Если игрок просто выйдет, его убьет, не зависимо от причин
    kill-reasons:
      - "АнтиЧит"
      - "anticheat"
      - "Читер"
      - "Подозрения в использовании"

  disable:
    fly: true
    speed: true
    gamemode: false
    godmode: false
    elytra: false
    invisibility: false

  cancel:
    interact: true
    command: true
    teleport: true
    chorus: false
    ender-pearl: false
    ender-chest: true

  # Работает только если cancel.command ровно true
  command-whitelist:
    - "msg"
    - "m"
    - "tell"
    - "pm"

  disabled-worlds:
    - "duels"
    - "duel"
    - "exampleWorld"

  # Предотвращает убийство игроков при выходе с сервера, если сервер залагал к примеру
  protect: true

messages:
  start: "§x§E§3§2§6§3§6&l| &fВы начали PvP!"
  end: "§x§E§3§2§6§3§6&l| &aВы больше не находитесь в бою."
  block: "§x§E§3§2§6§3§6&l| &cВы не можете делать это в режиме PvP!"




