# https://discord.gg/6wGy3sYxzw

settings:
  # Длительность режима PvP
  time: 25

  bossbar:
    bar: "&fРежим §x§E§3§2§6§3§6PvP &f- §x§E§3§2§6§3§6{time} сек"
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
    color: RED
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
    style: SOLID

  leave:
    kill: true
    # null или [] чтобы отключить
    message:
      - "&r"
      - "§x§E§3§2§6§3§6&l| &fИгрок §x§E§3§2§6§3§6{player}, &fпокинул сервер во время PvP!"
      - "&r"
    # Игрока будет убивать за выход с сервера, если leave.kill включен.
    # Но если игрока кикнет его убьет только в случае данных причин.
    kill-reasons:
      - "АнтиЧит"
      - "anticheat"
      - "Читер"
      - "Подозрения в использовании"

  # Что будет отключено в начале боя
  disable:
    fly: true
    speed: false
    gamemode: false
    godmode: false
    elytra: false
    invisibility: false

  # Какие действия нужно отменять во время боя
  cancel:
    interact: true
    command: true
    teleport: true
    chorus: false
    ender-pearl: false
    ender-chest: true

  # -1 или 0 отключает задержку
  cooldown:
    golden-apple: 0
    enchanted-golden-apple: 0
    ender-pearl: 0
    chorus: 0
    firework: 0
    totem: 0

  # Работает только если cancel.command ровно true
  command-whitelist:
    - "msg"
    - "m"
    - "tell"
    - "pm"

  # Миры в которых плагин не будет работать
  disabled-worlds:
    - "duels"
    - "duel"
    - "exampleWorld"

messages:
  start: "§x§E§3§2§6§3§6&l| &fВы начали PvP!"
  end: "§x§E§3§2§6§3§6&l| &aВы больше не находитесь в бою."
  block: "§x§E§3§2§6§3§6&l| &cВы не можете делать это в режиме PvP!"
  cooldown: "§x§E§3§2§6§3§6&l| &fПодождите §x§E§3§2§6§3§6{time}, &fчтобы использовать этот предмет!"



