name: powerantirelog
version: '${project.version}'
main: me.katze.powerantirelog.AntiRelog
api-version: '1.16'
authors: [katze225]
website: https://github.com/katze225/PowerAntiRelog/
description: AntiRelog plugin for your server
softdepend:
  - CMI
  - WorldGuard
  - Essentials