name: bloodmineantirelog
version: '${project.version}'
main: ru.bloodmine.bloodmineantirelog.AntiRelog
api-version: '1.16'
authors: [BloodMine, TheDiVaZo]
website: 'https://github.com/BloodMineCloud/BloodMineAntiRelog'
description: AntiRelog plugin for your server
softdepend:
  - CMI
  - WorldGuard